name: 'Cache Save action'
description: 'Saves caches of build artifacts.'
author: 'Andrew Kaster <akaster@serenityos.org>'
inputs:
  arch:
    description: 'Target Architecture to restore caches for'
    required: false
    default: 'x86_64'
  toolchain:
    description: 'Toolchain to restore caches for'
    required: false
    default: 'gcc'
  serenity_ccache_path:
    description: 'Path to the SerenityOS ccache directory'
    required: false
    default: ''
  toolchain_ccache_path:
    description: 'Path to the toolchain ccache directory'
    required: false
    default: ''

  toolchain_cache_primary_key:
    description: 'Primary key for the toolchain cache'
    required: true
  toolchain_cache_hit:
    description: 'Whether the toolchain cache was hit'
    required: true
  toolchain_cache_path:
    description: 'Path to the cached toolchain'
    required: true
  qemu_cache_primary_key:
    description: 'Primary key for the AArch64 QEMU cache'
    required: true
  qemu_cache_hit:
    description: 'Whether the AArch64 QEMU cache was hit'
    required: true
  serenity_ccache_primary_key:
    description: 'Primary key for the Serenity ccache'
    required: true
  toolchain_ccache_primary_key:
    description: 'Primary key for the Toolchain ccache'
    required: true

runs:
  using: "composite"
  steps:
    - name: 'Toolchain Prebuilt Cache'
      uses: actions/cache/save@v4
      # Do not waste time and storage space by updating the toolchain cache from a PR,
      # as it would be discarded after being merged anyway.
      if: ${{ github.event_name != 'pull_request' && !inputs.toolchain_cache_hit && inputs.arch != 'Lagom' }}
      with:
        path: ${{ inputs.toolchain_cache_path }}
        key: ${{ inputs.toolchain_cache_primary_key }}

    # FIXME: Remove manually built QEMU when we bump QEMU to >=8.1.x
    - name: 'AArch64 QEMU Cache'
      uses: actions/cache/save@v4
      if: ${{ github.event_name != 'pull_request' && inputs.arch == 'aarch64' && !inputs.qemu_cache_hit }}
      with:
        path: ${{ github.workspace }}/Toolchain/Local/${{ inputs.arch }}/qemu
        key: ${{ inputs.qemu_cache_primary_key }}

    - name: 'Toolchain Compiler Cache'
      uses: actions/cache/save@v4
      if: ${{ github.event_name != 'pull_request' && inputs.toolchain_ccache_path != '' }}
      with:
        path: ${{ inputs.toolchain_ccache_path }}
        key: ${{ inputs.toolchain_ccache_primary_key }}

    - name: 'Prune obsolete ccache files'
      shell: bash
      if: ${{ inputs.serenity_ccache_path != '' }}
      run: |
        CCACHE_DIR=${{ inputs.serenity_ccache_path }} ccache --evict-older-than=1d

    - name: 'Serenity Compiler Cache'
      uses: actions/cache/save@v4
      if: ${{ inputs.serenity_ccache_path != '' }}
      with:
        path: ${{ inputs.serenity_ccache_path }}
        key: ${{ inputs.serenity_ccache_primary_key }}

    - name: 'Cache Stats'
      shell: bash
      run: |
        echo "Serenity Compiler Cache"
        CCACHE_DIR=${{ inputs.serenity_ccache_path }} ccache -s

        echo "Toolchain Compiler Cache"
        CCACHE_DIR=${{ inputs.toolchain_ccache_path }} ccache -s
