name: Package the js repl as a binary artifact

on: [push]

env:
  SERENITY_SOURCE_DIR: ${{ github.workspace }}

jobs:
  build-and-package:
    runs-on: ${{ matrix.os }}
    if: always() && github.repository == 'SerenityOS/serenity' && github.ref == 'refs/heads/master'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        package_type: [Linux-x86_64]
        os_name: [Linux]
        include:
          - os: macos-14
            package_type: macOS-universal2
            os_name: macOS

    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}
      cancel-in-progress: true

    steps:
      - name: Checkout SerenityOS/serenity
        uses: actions/checkout@v4

      - name: "Set up environment"
        uses: ./.github/actions/setup
        with:
          os: ${{ matrix.os_name }}
          arch: 'Lagom'

      # NOTE: We don't restore ccache here, the Lagom ccache will have ASAN/UBSAN
      - name: Data Caches
        uses: ./.github/actions/cache-restore
        with:
          os: ${{ matris.os_name }}
          arch: 'Lagom'
          with_remote_data_caches: true
          download_cache_path: ${{ github.workspace }}/caches

      - name: Create build directory Ubuntu
        run: |
          cmake -S Meta/Lagom -B Build -G Ninja \
            -DCMAKE_C_COMPILER=gcc-13 \
            -DCMAKE_CXX_COMPILER=g++-13 \
            -DBUILD_LAGOM=ON
            -DSERENITY_CACHE_DIR=${{ github.workspace }}/caches
        if: ${{ matrix.os == 'ubuntu-22.04' }}

      - name: Create build directory macOS
        run: |
          # Note: We are using Apple Clang to create Universal binary
          cmake -S Meta/Lagom -B Build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET="11.0" \
            -DBUILD_LAGOM=ON
            -DSERENITY_CACHE_DIR=${{ github.workspace }}/caches
        if: ${{ matrix.os == 'macos-14' }}

      - name: Build and package js
        working-directory: Build
        run: |
          ninja js
          cpack

      - name: Upload js package
        uses: actions/upload-artifact@v4
        with:
          name: serenity-js-${{ matrix.package_type }}
          path: Build/serenity-js*.tar.gz
          retention-days: 7
