name: Build Wasm Modules
on: [ push, pull_request ]

env:
  SERENITY_SOURCE_DIR: ${{ github.workspace }}

concurrency: wasm

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.repository == 'SerenityOS/serenity'
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: "Install Ubuntu dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build gcc-13 g++-13 libstdc++-13-dev
      - name: "Install emscripten"
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.25
      - name: "Check versions"
        run: |
          set +e
          emcc --version
          ninja --version
          gcc --version
      - name: Checkout SerenityOS/libjs-data libjs-wasm
        uses: actions/checkout@v4
        with:
          repository: SerenityOS/libjs-data
          path: libjs-data
          ref: libjs-wasm

      - name: Data Caches
        uses: ./.github/actions/cache-restore
        with:
          os: 'Linux'
          arch: 'x86_64'
          with_remote_data_caches: true
          download_cache_path: ${{ github.workspace }}/Build/caches

      - name: "Build host lagom tools"
        run: |
          cmake -GNinja \
            -B ${{ github.workspace }}/Build/lagom-tools \
            -S ${{ github.workspace }}/Meta/Lagom \
            -DBUILD_LAGOM=OFF \
            -DSERENITY_CACHE_DIR=${{ github.workspace }}/Build/caches \
            -DCMAKE_C_COMPILER=gcc-13 \
            -DCMAKE_CXX_COMPILER=g++-13 \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/Build/lagom-tools \
            -Dpackage=LagomTools

          ninja -C ${{ github.workspace }}/Build/lagom-tools install
      - name: "Create wasm build environment"
        run: |
          emcmake cmake -GNinja \
            -B ${{ github.workspace }}/Build/wasm \
            -S ${{ github.workspace }}/Meta/Lagom \
            -DLagomTools_DIR=${{ github.workspace }}/Build/lagom-tools/share/LagomTools \
            -DBUILD_LAGOM=ON \
            -DSERENITY_CACHE_DIR=${{ github.workspace }}/Build/caches \
            -DBUILD_SHARED_LIBS=OFF
      - name: "Build libjs.{js,wasm}"
        run: |
          ninja -C ${{ github.workspace }}/Build/wasm libjs.js
      - name: "Show me what you built :)"
        run: |
          ls -l ${{ github.workspace }}/Build/wasm

      - name: "Prepare files"
        run: |
          cp ${{ github.workspace }}/Build/wasm/bin/libjs.js ${{ github.workspace }}/libjs-data/libjs.js
          cp ${{ github.workspace }}/Build/wasm/bin/libjs.wasm ${{ github.workspace }}/libjs-data/libjs.wasm
          echo 'Module.SERENITYOS_COMMIT = "${{ github.sha }}";' >> ${{ github.workspace }}/libjs-data/libjs.js
          tar --exclude='.[^/]*' -czvf libjs-wasm.tar.gz -C ${{ github.workspace }}/libjs-data .

      - name: Deploy to GitHub
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        if: github.ref == 'refs/heads/master'
        with:
          git-config-name: BuggieBot
          git-config-email: buggiebot@serenityos.org
          branch: libjs-wasm
          repository-name: SerenityOS/libjs-data
          token: ${{ secrets.BUGGIEBOT_TOKEN }}
          folder: ${{ github.workspace }}/libjs-data

      - name: Upload artifact package
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: serenity-js-wasm
          path: libjs-wasm.tar.gz
          retention-days: 7
